Repository firedancer-io/firedancer, pull requests merged in 2023-05, with the labels that each got.

#180 ballet: test sha for >4GiB inputs
  src/ballet/sha256/test_sha256.c
  src/ballet/sha512/test_sha512.c
Labels: crypto

#240 ballet: add blake3 support
  src/ballet/blake3/Local.mk
  src/ballet/blake3/blake3.c
  src/ballet/blake3/blake3.h
  src/ballet/blake3/blake3_avx2.c
  src/ballet/blake3/blake3_avx2_x86-64.S
  src/ballet/blake3/blake3_dispatch.c
  src/ballet/blake3/blake3_impl.h
  src/ballet/blake3/blake3_portable.c
  src/ballet/blake3/fd_blake3.c
  src/ballet/blake3/fd_blake3.h
  src/ballet/blake3/fd_blake3_portable.c
  src/ballet/blake3/fd_blake3_test_vector.c
  src/ballet/blake3/test_blake3.c
  src/ballet/fd_ballet.h
Labels: crypto, sealevel

#347 deps.sh: add bzip2, RocksDB
  deps.sh
Labels: dependencies
